### ISSUE TITLE
Getting rid of osu!api

### ISSUE THREAD

**Issue by l3lackShark** [FukutoTojido/TryZCustomOverlay#5]
Hello! Please list anything that's currently powered by osu api and that you have plans for. I would like to get rid of it completely, replacing with memory reading.

**Comment by FukutoTojido** [comment]
Things that were powered by osu! API are:
- User's ID (to get User's Avatar)
- User's Global PP
- User's Global Rank
- User's Country
I used to have an idea of fetching in-game leaderboard avatar but I'm afraid of that abusing the API system so I got rid of that.
Anyway I removed the API thing. Waiting for new gosumemory update. Thank you sir.
