### ISSUE TITLE
PP Counter, HP Bar etc dont show back after hidden, only leaderboard and UR

### ISSUE THREAD

**Issue by shoraaa** [FukutoTojido/TryZCustomOverlay#6]
Top and bottom bar hidden and never show back again :(

**Comment by FukutoTojido** [comment]
Can you replicate the issue and send me a video of it? Maybe you turned on Game Interface through Shift+Tab hotkey combination. Try pressing Shift+Tab while in game.

**Comment by shoraaa** [comment]
> Can you replicate the issue and send me a video of it? Maybe you turned on Game Interface through Shift+Tab hotkey combination. Try pressing Shift+Tab while in game.

Thanks, fixed it :). Dont know turning off Game Interface was a requirement.
